### ISSUE TITLE
license

### ISSUE THREAD

**Issue by isaacs** [zkat/maybe-hugs#39]
I think that it would make sense for this license to use the [Free As In Hugs License](http://blog.izs.me/post/48281002063/free-as-in-hugs-licence).  It doesn't have OSI acceptance yet, but it seems like a natural fit for the purposes of this module.

If you agree, happy to send a PR.

**Comment by zkat** [comment]
This should be fine. The current license is CC0, which I believe should allow a more restrictive license to be used. I'll definitely take a PR for this, since it keeps with the spirit of the repo :D
