### ISSUE TITLE
What is a maybe hug?

### ISSUE THREAD

**Issue by ghost** [zkat/maybe-hugs#6]

**Comment by zkat** [comment]
Sometimes, you want to offer someone a hug. Maybe they're cute and you like them. Maybe they feel bad and you want to comfort them. Some humans like physical contact. Some don't. Some like them from you, and some might prefer them from someone else. Maybe they just don't feel like being touched _right now_ even though they usually love hugs.

So this repo is for writing code that shows others how to be empathic but respectful and consent-oriented. It's supposed to make the world a cuter, gentler place.

Does that answer your question?

**Comment by zkat** [comment]
I thought this was a good question to ask, so I've added a slightly-improved explanation to `README.md` that we can improve further over time :)

**Comment by ghost** [comment]
Yes, it does :smile: 

Thanks.

**Comment by zkat** [comment]
great! have a good one!
